function cameraParams = calibrationDemo1()
%
%  Input(s): 
%  Output(s): 
%           cameraParams - parameters of the camera for demo 1 obtained
%                          through calibration
%

    % Define images to process
    imageFileNames = {strcat(pwd,'/Dataset/Demo1/calib/IMG_0001.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0002.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0003.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0004.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0005.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0006.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0008.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0009.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0010.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0011.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0012.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0013.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0014.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0015.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0016.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0023.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0024.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0026.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0027.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0028.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0030.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0031.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0032.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0033.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0034.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0035.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0038.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0041.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0042.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0043.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0044.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0057.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0058.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0060.jpg'),...
        strcat(pwd,'/Dataset/Demo1/calib/IMG_0064.jpg'),...
        };

    % Detect checkerboards in images
    [imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
    imageFileNames = imageFileNames(imagesUsed);

    % Read the first image to obtain image size
    originalImage = imread(imageFileNames{1});
    [mrows, ncols, ~] = size(originalImage);

    % Generate world coordinates of the corners of the squares
    squareSize = 20;  % in units of 'centimeters'
    worldPoints = generateCheckerboardPoints(boardSize, squareSize);

    % Calibrate the camera
    [cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
        'EstimateSkew', true, 'EstimateTangentialDistortion', false, ...
        'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'centimeters', ...
        'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
        'ImageSize', [mrows, ncols]);

    % View reprojection errors
    %h1=figure; showReprojectionErrors(cameraParams);

    % Visualize pattern locations
    %h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

    % Display parameter estimation errors
    %displayErrors(estimationErrors, cameraParams);

    % For example, you can use the calibration data to remove effects of lens distortion.
    %undistortedImage = undistortImage(originalImage, cameraParams);
end